// This file was generated by a custom prisma generator, do not edit manually.
export const UserRole = {
  ADMIN: "ADMIN",
  USER: "USER",
  HEALTHCARE_PROFESSIONAL: "HEALTHCARE_PROFESSIONAL",
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];
