// This file was generated by a custom prisma generator, do not edit manually.
export const UserRole = {
  ADMIN: "ADMIN",
  USER: "USER",
  HEALTHCARE_PROFESSIONAL: "HEALTHCARE_PROFESSIONAL",
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const AppointmentStatus = {
  PENDING: "PENDING",
  SCHEDULED: "SCHEDULED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export type AppointmentStatus = (typeof AppointmentStatus)[keyof typeof AppointmentStatus];
